version: "2"
services:
  web:
    build: .
    ports:
      - "5050:5050"
    expose:
      - "5050"
    environment:
      - PYTHONUNBUFFERED=0
    links:
      - mongo-db
    depends_on:
      - mongo-db
    volumes:
      - .:/app
    working_dir: /app
    command: python main.py

  mongo-db:
    image: mongo:4.1.1
    logging:
      driver: none
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./db:/data/db
